# Generated by Django 4.0.10 on 2023-08-26 16:33

from django.db import migrations, models
import rsautoglas.ycms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('header', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=700)),
                ('buttonText', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='fileentry',
            name='place',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='galerie',
            name='place',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galeryimage',
            name='upload',
            field=models.ImageField(upload_to=rsautoglas.ycms.models.upload_to_galery_image),
        ),
    ]
