# Generated by Django 4.0.10 on 2023-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0003_alter_fileentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
